// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using worker;

#nullable disable

namespace worker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("worker.Entities.Attack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AttackDatetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("attack_datetime");

                    b.Property<JsonDocument>("AttackLog")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attack_log");

                    b.Property<int>("AttacksRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("attacks_remaining");

                    b.Property<int>("Cycle")
                        .HasColumnType("integer")
                        .HasColumnName("cycle");

                    b.Property<string>("PlayerCode")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("player_code");

                    b.Property<int>("RaidId")
                        .HasColumnType("integer")
                        .HasColumnName("raid_id");

                    b.Property<JsonDocument>("RaidState")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raid_state");

                    b.Property<long>("TotalDamage")
                        .HasColumnType("bigint")
                        .HasColumnName("total_damage");

                    b.HasKey("Id")
                        .HasName("pk_attacks");

                    b.HasIndex("PlayerCode")
                        .HasDatabaseName("ix_attacks_player_code");

                    b.HasIndex("RaidId")
                        .HasDatabaseName("ix_attacks_raid_id");

                    b.ToTable("attacks", (string)null);
                });

            modelBuilder.Entity("worker.Entities.Clan", b =>
                {
                    b.Property<string>("ClanCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clan_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ClanCode")
                        .HasName("pk_clans");

                    b.ToTable("clans", (string)null);
                });

            modelBuilder.Entity("worker.Entities.MoraleTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("ClanCode")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clan_code");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PlayerCode")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("player_code");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("pk_morale_transactions");

                    b.HasIndex("ClanCode")
                        .HasDatabaseName("ix_morale_transactions_clan_code");

                    b.HasIndex("PlayerCode")
                        .HasDatabaseName("ix_morale_transactions_player_code");

                    b.ToTable("morale_transactions", (string)null);
                });

            modelBuilder.Entity("worker.Entities.Player", b =>
                {
                    b.Property<string>("PlayerCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("player_code");

                    b.Property<string>("ClanCode")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clan_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("PlayerCode")
                        .HasName("pk_players");

                    b.HasIndex("ClanCode")
                        .HasDatabaseName("ix_players_clan_code");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("worker.Entities.PlayerCardLevel", b =>
                {
                    b.Property<string>("PlayerCode")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("player_code");

                    b.Property<string>("CardId")
                        .HasColumnType("text")
                        .HasColumnName("card_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("PlayerCode", "CardId")
                        .HasName("pk_player_card_levels");

                    b.ToTable("player_card_levels", (string)null);
                });

            modelBuilder.Entity("worker.Entities.Raid", b =>
                {
                    b.Property<int>("RaidId")
                        .HasColumnType("integer")
                        .HasColumnName("raid_id");

                    b.Property<string>("ClanCode")
                        .IsRequired()
                        .HasColumnType("character varying(20)")
                        .HasColumnName("clan_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EnemyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("enemy_id");

                    b.HasKey("RaidId")
                        .HasName("pk_raids");

                    b.HasIndex("ClanCode")
                        .HasDatabaseName("ix_raids_clan_code");

                    b.ToTable("raids", (string)null);
                });

            modelBuilder.Entity("worker.Entities.RawEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("EventData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_data");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("worker.Entities.Attack", b =>
                {
                    b.HasOne("worker.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attacks_players_player_code");

                    b.HasOne("worker.Entities.Raid", "Raid")
                        .WithMany("Attacks")
                        .HasForeignKey("RaidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attacks_raids_raid_id");

                    b.Navigation("Player");

                    b.Navigation("Raid");
                });

            modelBuilder.Entity("worker.Entities.MoraleTransaction", b =>
                {
                    b.HasOne("worker.Entities.Clan", "Clan")
                        .WithMany("MoraleTransactions")
                        .HasForeignKey("ClanCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_morale_transactions_clans_clan_code");

                    b.HasOne("worker.Entities.Player", "Player")
                        .WithMany("MoraleTransactions")
                        .HasForeignKey("PlayerCode")
                        .HasConstraintName("fk_morale_transactions_players_player_code");

                    b.Navigation("Clan");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("worker.Entities.Player", b =>
                {
                    b.HasOne("worker.Entities.Clan", "Clan")
                        .WithMany("Players")
                        .HasForeignKey("ClanCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_players_clans_clan_code");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("worker.Entities.PlayerCardLevel", b =>
                {
                    b.HasOne("worker.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_card_levels_players_player_code");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("worker.Entities.Raid", b =>
                {
                    b.HasOne("worker.Entities.Clan", "Clan")
                        .WithMany()
                        .HasForeignKey("ClanCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_raids_clans_clan_code");

                    b.Navigation("Clan");
                });

            modelBuilder.Entity("worker.Entities.Clan", b =>
                {
                    b.Navigation("MoraleTransactions");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("worker.Entities.Player", b =>
                {
                    b.Navigation("MoraleTransactions");
                });

            modelBuilder.Entity("worker.Entities.Raid", b =>
                {
                    b.Navigation("Attacks");
                });
#pragma warning restore 612, 618
        }
    }
}
